### ISSUE TITLE
what the difference between this and grpc-gateway?

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/grpc-httpjson-transcoding#11]

**Comment by lizan** [comment]
grpc-gateway is a generator that generate a go implementation of gRPC-JSON proxy so you can compile and use it solely.

This library doesn't requires the compilation step, it uses protobuf descriptors as config. It can be used as a components of existing proxy. [Google Cloud Endpoints](https://cloud.google.com/endpoints/docs/transcoding) and [gRPC-JSON transcoder filter](https://lyft.github.io/envoy/docs/configuration/http_filters/grpc_json_transcoder_filter.html) in [Envoy](https://github.com/lyft/envoy) are using this.
