### ISSUE TITLE
does this support "fill-in" default protobuf fields ?

### ISSUE THREAD

**Issue by jwfang** [grpc-ecosystem/grpc-httpjson-transcoding#12]
protobuf won't serialize fields which has default values.
this is no problem when both sides are using native protobuf codec,
but for json, it would be nice to have all fields, no matter default or not, present.

**Comment by lizan** [comment]
Currently we use default [`JsonPrintOptions`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions), we are also receiving similar requests from Cloud Endpoints side, and I will work on it when I have time. If you want it soon, PRs are welcome :)

**Comment by jwfang** [comment]
thank you for guide.
seems we only need to change the options, much simpler than i original thought.

should we just change the default to *always_print_primitive_fields*, or expose the whole *JsonPrintOptions* ?

**Comment by lizan** [comment]
I prefer exposing the options, so we can keep existing behavior consistent.
