### ISSUE TITLE
Supporting cmake

### ISSUE THREAD

**Issue by henriknj** [grpc-ecosystem/grpc-httpjson-transcoding#31]
Is the project open for supporting cmake in addition to bazel?

**Comment by qiwzhang** [comment]
Sure, as long as not breaking bazel.

**Comment by henriknj** [comment]
One challenge though is how to handle dependencies such as protobuf. Currently, the project rely on protobuf internals which is easily accessible when using bazel to handle dependencies. 

One way of solving this would be to handle third party dependencies in similar fashion to how grpc does - git submodules.

What do you think about that? or do you see another way of solving it?

**Comment by qiwzhang** [comment]
git submodule and bazel don't go together very well.  no,  not "git submodule"
