### ISSUE TITLE
Question: Behavior when path and body in HTTP request map to same field

### ISSUE THREAD

**Issue by sumukhs** [grpc-ecosystem/grpc-httpjson-transcoding#42]
I have a proto definition from the greeter sample modified to the below:
Note that the uri path has a segment for "more.inner_name" and the body also maps to the field "more".

```
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) 
  {
      option (google.api.http) = 
      {
        get: "/api1/{name}/{more.inner_name}"
        body: "more"
      };
  }
}

message HelloInner {
    string inner_name = 1;
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  HelloInner more = 2;
}

```

I am issuing a request:
`$ curl http://0.0.0.0:5000/api1/hh/printme -i -H "hello: brother" --raw --http1.1 --data '{"inner_name":"frombody"}' --request GET`

On the grpc server, what is the expected body content? I see that the inner_name is set to "**frombody**". Is this behavior guaranteed to remain this way or could the inner_name be "**printme**" in the future?

**Comment by sumukhs** [comment]
@lizan  any guidance here?

**Comment by qiwzhang** [comment]
As I remember the order is:  path_segment,   query_parameters and body
The latter will override the former.   query_parameter will override path_segment,
and body will override query_parameter.  and path_segment.

But I need to look at the code to confirm this.

**Comment by qiwzhang** [comment]
Yes, here is the unit-test [code](ExtractBindingsFromQueryParameters):

If there is collision, from query parameter and body json.   Its policy is collision Ignored.  It means the query parameter binding will be ignored.   Unless it is repeated field which is added.
