### ISSUE TITLE
UrlUnescapeString irreversabily transforms data

### ISSUE THREAD

**Issue by euroelessar** [grpc-ecosystem/grpc-httpjson-transcoding#44]
`UrlUnescapeString` produces the same output for semantically different strings, for example:
```
UrlUnescapeString("%2523", false) == "%23"
UrlUnescapeString("%23", false) == "%23"
```

This makes it impossible to understand original intent of a user.

**Comment by euroelessar** [comment]
@qiwzhang hi, any thoughts on this?

**Comment by qiwzhang** [comment]
Yes,  I agreed that this function may produce such result.  But I like to understand the issues, in the context of grpc transcoding actual usages.

**Comment by euroelessar** [comment]
It is impossible for a server behind transcoder to understand if path component's value is `foo/%23` or `foo/#`, this effectively is a data corruption. It also means that it's impossible for a user to send request with `foo/%2523` in its path, as it is silently converted to hashtag (or other way around, depending on the heuristic on server side which tries to reconstruct original data).

**Comment by euroelessar** [comment]
If it is hard/impossible to change the default behavior at this point, what is your opinion in regards to make it a configurable option to always decode all percent encoding? (regardless if it's multi-match or not)

**Comment by euroelessar** [comment]
Reading rfc6570, it looks like `%` character is always encoded, in both `{var}` and `{+var}` expansions.
Do I read it correctly?

```
   Note that the percent character ("%") is only allowed
   as part of a pct-encoded triplet and only for reserved/fragment
   expansion: in all other cases, a value character of "%" MUST be pct-
   encoded as "%25" by variable expansion.
```

**Comment by qiwzhang** [comment]
I am not fully understand the rc6570 and its implication on urlunescape.  But I think we may have a work around. I replied in https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/pull/45
