### ISSUE TITLE
Verbs are not distinguished from other segments

### ISSUE THREAD

**Issue by jaredkhan** [grpc-ecosystem/grpc-httpjson-transcoding#49]
Say I want to have resources such as:

`/people` (a collection of people)
`/people/{personId}`  (an individual person)

And I want both of these resource types to accept a custom verb called 'getResourceType'.

If someone makes a request to `/people:getResourceType` I want it to say 'person collection'
If someone makes a request to `/people/xyz:getResourceType`I want it to say 'person'

---

So my .proto might look like this:

```
service API {
  rpc ListPeople(Empty) returns (ListPeopleResponse) {
    option (google.api.http) = {
      get: "/people"
    };
  }
   
  rpc GetPerson(GetPersonRequest) returns (GetPersonResponse) {
    option (google.api.http) = {
      get: "/{person_id=people/*}"
    };
  }

  rpc GetResourceType(GetResourceTypeRequest) returns (GetResourceTypeResponse) {
    option (google.api.http) = {
      get: "/{resource_name=**}:getResourceType"
    };
  }
}

message GetPersonRequest {
  string person_id = 1;
}
message GetResourceTypeRequest {
  string resource_name = 1;
}
...
```

Then I might set up grpc-httpjson-transcoding using, say, Envoy.

**When**: I make a call to this service at `/people:getResourceType`

**Expected**: Service receives a GetResourceType call with resource_name = "people" (since that is the only method that accepts the getResourceType verb)

**Actual**: Service receives a GetPerson call with person_id = "getResourceType"

---

In my understanding, this is due to the ':' character being replaced with a '/' without remembering that the last segment is a verb.
https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/blob/master/src/include/grpc_transcoding/path_matcher.h#L376

**Comment by qiwzhang** [comment]
Yes,  you are right on the spot.  Let me see if there is any easy way to fix it.  Welcome any suggestion.

**Comment by nareddyt** [comment]
Can you double check if the path-matcher code here is in sync with ESPv2's path matcher (before we removed it)?

In ESPv2, we had tests for `**` with `:verb`

https://github.com/GoogleCloudPlatform/esp-v2/blob/44483422213bd465aeffdf98371a51a2d7d325f6/src/api_proxy/path_matcher/path_matcher_test.cc#L349

**Comment by qiwzhang** [comment]
@nareddyt ESPv2 path_matcher code is too much different with the one here.  Many transcoding features are removed.
